language: swift  #1
osx_image: xcode12.0 #2
xcode_project: WeatherApp.xcodeproj #3
xcode_scheme: WeatherApp #4
xcode_sdk: iphonesimulator14.4 #5

before_install:
  - bundle install
  - gem install linterbot
  - bundle exec pod install --repo-update
